apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: spark-pi-wf-
spec:
  entrypoint: spark-pi
  arguments:
    parameters:
    - name: queue
      value: root.default  # default value
    - name: image
      value: apache/spark:3.5.7
    - name: namespace
      value: yunikorn-spark-submit
    - name: partitions
      value: 10000
    - name: executors
      value: 1
    - name: scheduler
      value: default-scheduler
  templates:
  - name: spark-pi
    serviceAccountName: spark
    container:
      image: "{{workflow.parameters.image}}"
      command: ["/opt/spark/bin/spark-submit"]
      args:
      - --master
      - k8s://https://kubernetes.default.svc:443
      - --deploy-mode
      - cluster
      - --name
      - spark-pi
      - --conf
      - spark.kubernetes.container.image={{workflow.parameters.image}}
      - --conf
      - spark.kubernetes.namespace={{workflow.parameters.namespace}}
      - --conf
      - spark.kubernetes.authenticate.driver.serviceAccountName=spark
      - --conf
      - spark.executor.instances={{workflow.parameters.executors}}
      - --conf
      - spark.kubernetes.driver.request.cores=0.2
      - --conf
      - spark.kubernetes.driver.limit.cores=0.5
      - --conf
      - spark.driver.memory=1024m
      - --conf
      - spark.driver.memoryOverhead=200m
      - --conf
      - spark.kubernetes.executor.request.cores=0.2
      - --conf
      - spark.kubernetes.executor.limit.cores=0.5
      - --conf
      - spark.executor.memory=512m
      - --conf
      - spark.executor.memoryOverhead=100m
      - --conf
      - spark.kubernetes.scheduler.name={{workflow.parameters.scheduler}}
      - --conf
      - spark.kubernetes.driver.label.queue={{workflow.parameters.queue}}
      - --conf
      - spark.kubernetes.driver.label.yunikorn.apache.org/allow-preemption=false
      - --conf
      - spark.kubernetes.executor.label.queue={{workflow.parameters.queue}}
      - local:///opt/spark/examples/src/main/python/pi.py
      - "{{workflow.parameters.partitions}}"
