apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "apache/spark:3.5.7"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples.jar
  arguments:
    - "10000"  # Number of partitions (default is 2)
  sparkVersion: "3.5.7"
  batchScheduler: "volcano"   #Note: the batch scheduler name must be specified with `volcano`
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    coreRequest: "100m"
    coreLimit: "1000m"
    memory: "2g"        
    labels:
      version: 3.5.7
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    coreRequest: "100m"
    coreLimit: "1000m"
    instances: 8
    memory: "512m"
    labels:
      version: 3.5.7
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
