apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  log.level: "DEBUG"
  # admissionController.accessControl.bypassAuth: "true"
  admissionController.accessControl.systemUsers: '^kubernetes-admin$'
  queues.yaml: |
    partitions:
      - name: default
        preemption:
          enabled: true
        placementrules:
        - name: provided
          create: true
          filter:
            type: allow
            users:
              - spark
          parent:
            name: tag
            value: namespace
            parent:
              name: fixed
              value: root.yunikorn
        - name: fixed
          value: default
          create: true
          parent:
            name: tag
            value: namespace
            parent:
              name: fixed
              value: root.yunikorn
        - name: fixed
          value: root.yunikorn.default
        queues:
        - name: root
          submitacl: '*'
          queues: 
          - name: yunikorn
            parent: true
            childtemplate:
              resources:
                max:
                  vcore: 1500m
                  memory: 3Gi
            queues:
            - name: yunikorn-spark-operator
              resources:
                guaranteed:
                  {memory: 2Gi, vcore: 1000m}
                max:
                  {memory: 3Gi, vcore: 1500m}
              queues:
              - name: tenant-1
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
            - name: yunikorn-spark-submit
              resources:
                guaranteed:
                  {memory: 2Gi, vcore: 1000m}
                max:
                  {memory: 3Gi, vcore: 1500m}
              queues:
              - name: tenant-1
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
            - name: default
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}