apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  queues.yaml: |
    partitions:
      - name: default
        preemption:
          enabled: true
        placementrules:
        - name: provided
        - name: fixed
          value: root.default.default.default
        queues:
        - name: default
          queues:
          - name: default
            queues:
            - name: default
              submitacl: '*'
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
        - name: sit
          submitacl: '*'
          queues:
          - name: ns-1
            properties:
              priority.offset: "-1000"
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
            queues:
            - name: tenant-1
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
          - name: ns-2
            properties:
              priority.offset: "-1000"
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
            queues:
            - name: tenant-1
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
          - name: ns-3
            properties:
              priority.offset: "-1000"
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
            queues:
            - name: tenant-1
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
        - name: uat
          submitacl: '*'
          queues:
          - name: ns-1
            properties:
              priority.offset: "0"
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
            queues:
            - name: tenant-1
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
            - name: tenant-2
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
          - name: ns-2
            properties:
              priority.offset: "0"
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
            queues:
            - name: tenant-1
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
          - name: ns-3
            properties:
              priority.offset: "1000"
            resources:
              guaranteed:
                {memory: 2Gi, vcore: 1000m}
              max:
                {memory: 3Gi, vcore: 1500m}
            queues:
            - name: tenant-1
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}