apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: yunikorn
  name: yunikorn-admission-controller-mutations
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZIakNDQXdhZ0F3SUJBZ0lIQmtqTHNtRVFUekFOQmdrcWhraUc5dzBCQVFzRkFEQWVNUnd3R2dZRFZRUUsKRXhONWRXNXBhMjl5Ymk1aGNHRmphR1V1YjNKbk1CNFhEVEkyTURFeU1EQTJNRGMwT0ZvWERUSTJNRGN5TURBMgpNVEkwT0Zvd0hqRWNNQm9HQTFVRUNoTVRlWFZ1YVd0dmNtNHVZWEJoWTJobExtOXlaekNDQWlJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBTXVvYVVXZk9nenJkVzd2OWl4OTc0MDVONENhaXBRaEdQN3kKT0RTbS95WWZUU3ZHeWJzQTQvZm1melZUNHB5dllWVXVKb0NuYVhXLzlsUitIQllNVElrNG0rK29UL1NnQU9uOQpsTFBqTlltZVZJWTFUeGg4elZuYjB0SGMxVG1yUFdDYXp0L0ZiNmpULzZtdTNnR2VvRE1WSjI0bnc2RnBTaXkxCnUwbXBkcHVEck1kdjhlZGlnOUFSMEcrUUs5Ty9kbzVxR213d1hYZHdZa1pDajJwbzNYdzlKZnBXeEUvRWlmMkUKbWJZOUtmTTJyWEt0WVRJOTJDUys4Y0JVRHdJSFRoWmZSZURPUHdWcHAwNUdTclNNTG94OFN4WDErVEJvc0xDRAp3WjA4R3VQL2I5SW5IeGk4NUMrSzljRUswYVdhQUEzUGc4UWppRUFPaXBkTitrdC9Yb294WkRyYVp6UjRsZFdZCnQxRXJOTnBhQjdXMncyQnZVMlRiZysxUGxlN2dXYWR0Slh1aDVWa3VOWUVxMCt6ajdrQXc1UW5zdVRuM21UTGcKYW83bWs1dHk0QmJxZDRyeGVGLzA4WnBObER6ZnpRMVhpeFJCK1FWSWQ0b2tMMm9yczU3UXdQL2tFM0ZuQWtCRgpTb25weXdBWVVXdDYvUWJNVXZNNEFJZHpBS0lxUG1RNXdNbDlSM3ZiSDAwMzBPekQxZFYxYlEwT2dFU2xzWjVOCnlmSStzcitjQTZoOXVIenFFbm5hZktWNHM2d2hCd3RyOHBDcktwdENpRS92ZlBndFdOeER0dXhzcDZ5VXBYVy8KZHQxTFZLTk8wNzlod1lDb0FOQ0dpTERxd1JqcEM1Qk1Ra2Z1ZmkyRFlEanZtalNranFBRGlPSmhjK2VZb3VpUgpKSllRRTNCTEFnTUJBQUdqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGCkJRY0RBZ1lJS3dZQkJRVUhBd0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVN0MvbWJuYS8KNVhIRWozMkxwM3dPZlhUeHJFVXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBQVJPazZodllpN2R1RlRUMUVYLwpkWXRWQVhQUCtYZFZNMnJTYlNaYWliUzI2c3VaamV3d2srUkg3ZlBOTGI4UFk1dVdjbXV3bUgzVlhtNGY3VGhCCkNOK2tFdFdRLy8yVjBqaFh0d21kSHlhVE55VzA4K1VHRnlDNnVVeTNqYSt2VTdneXRrT2Y1Z2xqQmFHMHMwa28KTW5yWHp0ZDYzTUtqSlMzQkhCZzVHcTJURnRiOE5xYWtVSkhvNkd4SHZhTUFUUk52WXZhVStXNnVSWENUMW5HTwpZS3dCQ3NKbmNPb0pDL0ltMlVraXBtUWxwVVZtbkYzQUNHWmdiU1BWUExoS0tQUnRLMitmK3g3RC9paGlUSFYyCjUzV3lCd2xCQlFUU1Y5dld1eG1iejNpVDUvTXBQVzdlZm9oUXJrb2Z5Zko4MXFsZ2kySXpVN1IyaXZ2Z3diR3IKK3FDTDVVYzJMM0ExNVN4UFFxek5QVTdOUDZLK09WNlVHU25WbkMzWTVqUUtXWDM4M1R0cUxtZGVlS3N4QnRwRQpxd2ZCSnFKRlUxeHJsNERtTmg3SVQ0dC96Y3k2VElRRkxJZW5EUVlBTGo4MjlZQ2dwNUdOREZIL2VBYU1oZEJXCis1aHBMZFdUcHVNVU1YdzFKRmZSRklMdWJNU29pcVJjOXVtYmZ0SkYzNGE0MlJnSmlYUDZ3d2F5c2pjZTE3S28KTVg5SmVNUUpXbUF3N3Z6aW9PRVZRUUpMdm0xdkZwSDdwUWdhSDUreStpUDVUUU1PVXNmNHNQWW1mWWFOUWs5WAo4eUJoQTRUa1NUbnNkQXhzY2NDaUhOTDIwWHUwdHVpYWZRL3ZXczIrb25RbVpSd2tIQXNUdWplMFUzNkV6TExiCmlRbUdNdWVWa3Z1dmg1dDY1dXdKM3VxegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGSGpDQ0F3YWdBd0lCQWdJSEJrakxzbm9FZmpBTkJna3Foa2lHOXcwQkFRc0ZBREFlTVJ3d0dnWURWUVFLCkV4TjVkVzVwYTI5eWJpNWhjR0ZqYUdVdWIzSm5NQjRYRFRJMk1ERXlNREEyTURjMU1Gb1hEVEkzTURFeU1EQTIKTVRJMU1Gb3dIakVjTUJvR0ExVUVDaE1UZVhWdWFXdHZjbTR1WVhCaFkyaGxMbTl5WnpDQ0FpSXdEUVlKS29aSQpodmNOQVFFQkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUxxeUFSbUNOelJWQ2JXcGZubFU1NDZKdWk0V3AzWEZIdWp3CmY1U2pNT2dFZUFtZmJBTnBQRzIxYSsyL0oxbmdseEJxSC9yVzFTZHRYZ3lpcDVGdE1UMTBtdXBrd1hGbjdxazIKbTFUK1B2cXpIaW9lcHBOWStWSzQwK0VPK3JlRHkzWS91bjFXVU5IVXBkNENReEJhNzNPMWV4REtNRnNMVUtlbAppNVBsVEZLd3FQNmdjVEtsTFhhKzhHT3RMdE1qR0h4NlZEam1DeCsxeDF6aUY4bGV4bHpFVGo2MVkvZWpaYWttCkVaN2haM0xNVTc1RGJ3UlFtQmtwSXNnQmY0MTdiRnlYR0huSmpHTzRxWDhRbHR1K1prd0REeUhoSUx0c0dZamQKSXlNNTB3Y0FBTlpvWUx1dGs0Y2N3Ujh1T2E0NXE1SkdsaDg0VStsbndLU0J2VUhsSUpoZmdyd24xcjBTUjk0RgpxVDdNVE1tZElUa1VjRlZKLy9qeUdpV3ZTVU9ZN3RybkZSV3dQMUxxMnhzRXZoTWxXa3dvdFFYcmdWWVg0Unk1Ci80bW5NblcwVlZaMWtmQVVrdnlvRGV0aVVkVWxtdUZTWHlCMmtCZnRKYUNMdnNaZ3RCbTBBQ1dsOEdHSnhUVGEKam5QNUY1Q0Q5eEFDb2UvRDFScFM3aThVRGFpeTZTY1hWUUNwd045MlBjY2xuS0xvUGQ0R1RPRlVmc2xXYlk5TAo3WFJ3dFplaU9aaTAxM0Jubzd3OWs4YmN3WmpqbndsUFJMVFpEd2ZtTGpSbnIxYVhwdjVnTVBiQkExVFZubDFrCk9NbWdUVnhLbmVGaG00QzBSYlZJNUhIcUI4NjM5Zlo1dnlNQVFFS2NMYytwZjlUK0x0cTZKQmd6SjRLYWcrMkIKbFF5VUdnVGRBZ01CQUFHallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRgpCUWNEQWdZSUt3WUJCUVVIQXdFd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWpINHFva2RICnJzV0xtYVM3RGtBRWg1RVpWZ2d3RFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUJIa3ViOFNxK2MzNVR3S0VQTDMKQTMyQjJJY09OdDdSQXNjUldOR0RqQlV0MFp5ZEJkb0F3Rko4blhnZG9EVUd5VVJPUm1YcVZGbHovMUVKTVp2QQpJN0ZtUVE4WXRxbHJlZmx4d3M0WHlsb0tzVnpqeGVYVXljRlhvelMvV3VpVW02eTFyTlU2VVF5eGs0N1hjUWFkCkJOYThKNS9pSktaUGpiRllIRVpWMmRpeGJLRTRzanVqSTl0OUtLaGdhZUk2WnBMTDRlK2RFSktuSVZqeFh2UncKT2xuYW81SnJ6aDgxWjJMQmRBb3N5ZzJPMUwvL0lNRSs1a0Z2VE5LamNzZ1lkdkV1N3Exd0J4cDJpNVFyK2ZadgpSeDIzNWpxWTZvZ2tWKzBkQUx5SEFuT0tEUUEwUEtkV2N3bG0xM21pQ3p6bWdpRDdzS20wV3ZrYUR3YzkvS0xLCkZxbmcvbFpiNUhmM0xYNmEvaTg0MU5MMFZWbXFrUysxcUh1UERCeFI3K0VlTTdDTHNMN1dnNkphVmdSOU1HeWQKWWRhY0hXQ1IrYlprSTdmZ21ldElwOEtid1plcGJRNDBVRWl4Y1E0UFlRc05TeWUwWDVTZE95dFdudUtEbkU5Sgp6amJVVWhyY2J1TXhucG9EZTZ1T25mUkFEeHlva3VHNjcrM1dGUFYxaFo4VldVTjNjdW9Hc1NkSDFDQlVPc1FhClFUaEJEZDNnay81dzlOVlRaMzdTRnR3NVRZSGFjWFBjTlJ3ZzFSV3FOMSszMUNaLzhDRHFXR1dkb2ZVNjFuQTUKWE1pVXJhY3ArbWFjaDkzZ084ZXNsUWttb1ptenlYNjJremRzbmQxR2dUVy93bnBpV3Ewc09XNTZzRC9IQUJYMwoyWWU4Q3BoNzNuYk93T0l6dEJVL1FHbkkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: yunikorn-admission-controller-service
      namespace: yunikorn
      path: /mutate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: admission-webhook.yunikorn.mutate-pods
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - namespace-1
      - namespace-2
      - namespace-3
  # namespaceSelector:
  #   matchLabels:
  #     kubernetes.io/metadata.name: default
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    - apps
    - batch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
    - jobs
    - cronjobs
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
