apiVersion: v1
kind: ConfigMap
metadata:
  name: yunikorn-configs
  namespace: yunikorn
data:
  log.level: "DEBUG"
  admissionController.accessControl.systemUsers: '^kubernetes-admin$,^system:serviceaccount:argo:.*$'
  admissionController.filtering.processNamespaces: "^yunikorn-"
  queues.yaml: |
    partitions:
      - name: default
        preemption:
          enabled: true
        placementrules:
        - name: provided
          create: true
          filter:
            type: allow
            users:
              - spark
          parent:
            name: tag
            value: namespace
            parent:
              name: fixed
              value: root.yunikorn
        - name: fixed
          value: default
          create: true
          parent:
            name: tag
            value: namespace
            parent:
              name: fixed
              value: root.yunikorn
        - name: fixed
          value: root.yunikorn.default
        queues:
        - name: root
          submitacl: '*'
          properties:
            preemption.delay: "3s"
          queues: 
          - name: yunikorn
            parent: true
            queues:
            - name: default
              resources:
                guaranteed:
                  {memory: 1Gi, vcore: 500m}
                max:
                  {memory: 3Gi, vcore: 1500m}
            - name: yunikorn-spark-operator
              childtemplate:
                properties:
                  preemption.delay: "3s"
                  preemption.policy: "default"
                  priority.offset: "0"
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
                  max:
                    {memory: 3Gi, vcore: 1500m}
              resources:
                guaranteed:
                  {memory: 2Gi, vcore: 1000m}
                max:
                  {memory: 3Gi, vcore: 1500m}
              queues:
              - name: tenant-1
                properties:
                  preemption.delay: "3s"
                  preemption.policy: "default"
                  priority.offset: "0"
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
                  max:
                    {memory: 3Gi, vcore: 1500m}
            - name: yunikorn-spark-submit
              childtemplate:
                properties:
                  preemption.delay: "3s"
                  preemption.policy: "default"
                  priority.offset: "0"
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
                  max:
                    {memory: 3Gi, vcore: 1500m}
              properties:
                preemption.policy: "fence"
              resources:
                guaranteed:
                  {memory: 2Gi, vcore: 1000m}
                max:
                  {memory: 3Gi, vcore: 1500m}
              queues:
              - name: tenant-1
                properties:
                  preemption.delay: "3s"
                  preemption.policy: "default"
                  priority.offset: "0"
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
                  max:
                    {memory: 3Gi, vcore: 1500m}
              - name: tenant-2
                properties:
                  preemption.delay: "3s"
                  preemption.policy: "default"
                  priority.offset: "0"
                resources:
                  guaranteed:
                    {memory: 1Gi, vcore: 500m}
                  max:
                    {memory: 3Gi, vcore: 1500m}