apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-with-suspend-
  namespace: argo

spec:
  entrypoint: hello-and-wait
  templates:
  - name: hello-and-wait
    steps:
    - - name: hello1
        template: print-message
    - - name: wait1
        template: wait
    - - name: hello2
        template: print-message
    - - name: wait2
        template: wait
    - - name: hello3
        template: print-message

  - name: print-message
    metadata:
      labels:
        applicationId: "{{workflow.name}}"
        queue: "root.default"
        schedulerName: yunikorn
    container:
      image: busybox
      command: [echo]
      args: ["============================="]
  
  - name: wait
    suspend:
      duration: "28400ms"
