apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: many-steps-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: count
      value: "10"
    - name: sleep-seconds
      value: "30000"
    - name: cpu-request
      value: "100m"
    - name: cpu-limit
      value: "1000m"
    - name: memory-request
      value: "128Mi"
    - name: memory-limit
      value: "1280Mi"
    - name: queue
      value: root.yunikorn.yunikorn-spark-submit.tenant-1

  templates:
    - name: main
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: run-many
            template: sleep-pod
            arguments:
              parameters:
                - name: sleep-seconds
                  value: "{{workflow.parameters.sleep-seconds}}"
                - name: pod-id
                  value: "{{item}}"
            withSequence:
              count: "{{workflow.parameters.count}}"
    - name: sleep-pod
      inputs:
        parameters:
          - name: sleep-seconds
          - name: pod-id
      outputs: {}
      metadata:
        labels:
          applicationId: "{{workflow.name}}"
          queue: "{{workflow.parameters.queue}}"
        annotations:
          yunikorn.apache.org/user.info: '{"user": "spark"}'
      container:
        name: ""
        image: busybox
        command:
          - sh
          - -c
        args:
          - echo 'Pod {{inputs.parameters.pod-id}} sleeping for
            {{inputs.parameters.sleep-seconds}}s' && sleep
            {{inputs.parameters.sleep-seconds}}
        resources: {}
      serviceAccountName: spark
      podSpecPatch: |
        containers:
          - name: main
            resources:
              requests:
                cpu: "{{workflow.parameters.cpu-request}}"
                memory: "{{workflow.parameters.memory-request}}"
              limits:
                cpu: "{{workflow.parameters.cpu-limit}}"
                memory: "{{workflow.parameters.memory-limit}}"