apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job-${TIMESTAMP}
  # labels:
  #   applicationId: pi-job-${TIMESTAMP}
spec:
  completions: ${COMPLETIONS}
  parallelism: ${PARALLELISM}
  template:
    metadata:
      labels:
        applicationId: pi-job-${TIMESTAMP}
        queue: ${QUEUE}
      annotations:
        yunikorn.apache.org/user.info: '{"user": "spark"}'
    spec:
      schedulerName: yunikorn
      containers:
      - name: pi
        image: busybox:latest
        command: ["sleep", "${SLEEP_DURATION}"]
        resources:
          requests:
            memory: "${MIN_MEMORY}"
            cpu: "${MIN_CPU}"
          limits:
            memory: "${MAX_MEMORY}"
            cpu: "${MAX_CPU}"
      restartPolicy: Never
  backoffLimit: 999
